
export const CHANGE_TOP_TIP_TAB = 'CHANGE_TOP_TIP_TAB';

export const CHANGE_TOP_TIP_DIALOG = 'CHANGE_TOP_TIP_DIALOG';

export const CHANGE_TOP_TIP_ADDRESS = 'CHANGE_TOP_TIP_ADDRESS';

export const CHANGE_TOP_TIP_FILTERS = 'CHANGE_TOP_TIP_FILTERS';

export const CHANGE_TOP_TIP_KEYWORDS = 'CHANGE_TOP_TIP_KEYWORDS';

export const GET_JOBS_DATA = 'GET_JOBS_DATA';
